spring:
  profiles:
    active:
     - dev

---
spring:
  profiles: dev
  application:
    name:  microservicecloud-config-client
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka1.com:7001/eureka/
---
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka1.com:7001/eureka/
spring:
  profiles: test
  application:
    name:  microservicecloud-config-client
server:
  port: 8202